<template>
  <div class="home">
    <div class="l-text">
 <h1>NIKE </h1>
    <h3>POINT OF SALE</h3>
    </div>
   
<div class="linky">
 <router-link  to="/login">Login</router-link> 
    <router-link to="/register">Register</router-link>
</div>
    
  </div>
</template>

<script>

export default {
 
}
</script>

<style scoped>
.home{
  height: 100vh;
  padding-top: 5%;
  background-image: url("../assets/bg.jpg");
  /* background-repeat: no-repeat; */
  /* background-size: cover; 
  */

  background-position: 0px 0px;
  background-repeat: repeat-x;
  animation: animatedBackground 10s linear infinite alternate;
}
.l-text{
  color: red;
}
h1,h3{
   font-size: 50px;
}
a{
  border: none;
  border-radius: 25px;
  padding: 15px;
  padding-left: 100px;
   padding-right: 100px;
  margin:15px;
  width: 400px !important;
  color: red;
  text-decoration: none;
  background-color: rgb(167, 167, 167);
}
a:hover{
  color: black;
  border:solid 5px red;
}
.linky{
    position: fixed;
  bottom: 15%;
  left: 30%;
}

/* media qeury */
@media only screen and (max-width: 500px) {
a{
   padding-left: 50px;
   padding-right: 50px;
}
.linky{
    position: fixed;
  bottom: 15%;
  left: 20%;
}
}

/* animation */
@keyframes animatedBackground {
  from {
    background-position: 0 0;
  }
  to {
    background-position: 200% 0;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2022-2-27 16:2:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation kenburns-bottom
 * ----------------------------------------
 */
 .kenburns-bottom {
	-webkit-animation: kenburns-bottom 5s ease-out both;
	        animation: kenburns-bottom 5s ease-out both;
}
@-webkit-keyframes kenburns-bottom {
  0% {
    -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 84%;
            transform-origin: 50% 84%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(15px);
            transform: scale(1.25) translateY(15px);
    -webkit-transform-origin: bottom;
            transform-origin: bottom;
  }
}

@keyframes kenburns-bottom {
  0% {
    -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
    -webkit-transform-origin: 50% 84%;
            transform-origin: 50% 84%;
  }
  100% {
    -webkit-transform: scale(1.25) translateY(15px);
            transform: scale(1.25) translateY(15px);
    -webkit-transform-origin: bottom;
            transform-origin: bottom;
  }
}

</style>